pub const NOT_AUTHORIZED: felt252 = 'NOT_AUTHORIZED';
pub const NULLIFIER_USED: felt252 = 'NULLIFIER_USED';
pub const CAMPAIGN_INACTIVE: felt252 = 'CAMPAIGN_INACTIVE';
pub const CAMPAIGN_EXPIRED: felt252 = 'CAMPAIGN_EXPIRED';
pub const INSUFFICIENT_BUDGET: felt252 = 'INSUFFICIENT_BUDGET';
pub const INVALID_AMOUNT: felt252 = 'INVALID_AMOUNT';
